name: checks
description: check formatting of Python files as well as meta file generation status for Blender properties.

on:
    workflow_call:
        inputs:
            python-version:
                required: true
                type: string

jobs:
    check_format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ inputs.python-version }}

            - name: install dev requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: run format script in check mode
              run: |
                  python scripts/format.py --check
    check_generation_status:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ inputs.python-version }}

            - name: install dev requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: run generation file in check mode
              run: |
                  python scripts/generate_property_meta_files.py --check
